### ISSUE TITLE
CLI gives API error on running cached ad-hoc commit from a different project

### ISSUE THREAD

**Issue by JuhaKiili** [valohai/valohai-cli#104]
![Screenshot from 2019-10-29 13-45-05](https://user-images.githubusercontent.com/1525350/67764504-c8860780-fa52-11e9-97b5-3db230bb24fb.png)

Repro steps:
1. Run ad-hoc execution
2. Run it again (works)
3. Create & link new project `vh project create`
4. Run the execution again
5. API error occurs

**Comment by akx** [comment]
Likely a duplicate of valohai/roi#1243.

**Comment by JuhaKiili** [comment]
> Likely a duplicate of [valohai/roi#1243](https://github.com/valohai/roi/issues/1243).

Yup seems like the same thang
