### ISSUE TITLE
Suggested Docker images might not exist

### ISSUE THREAD

**Issue by orasimus** [valohai/valohai-cli#124]
I ran into a weird situation with a customer on Monday, the latest Tensorflow image suggested by `valohai-cli` when running `vh init` was `tensorflow/tensorflow:2.2.0-gpu-py3`. Our executions failed because an image with this tag doesn’t exist in Dockerhub (so we reverted to 2.0.1 manually), all 2.2.0 versions are with an “rc” in the name as well.

**Comment by akx** [comment]
The `valohai/images` list must be refreshed...
