### ISSUE TITLE
Some default string values in valohai.yaml pass the linting, but fail as internal error

### ISSUE THREAD

**Issue by JuhaKiili** [valohai/valohai-cli#128]
`valohai_cli.exceptions.APIError: Internal error`

Fail:
```
    - default: 2020-09-02T00:00:00.000000Z
      description: Start date
      name: ctime
      optional: false
      type: string
```

Success:
```
    - default: "2020-09-02T00:00:00.000000Z"
      description: Start date
      name: ctime
      optional: false
      type: string
```

**Comment by akx** [comment]
There're two options here – either actually lint `default` against the `type` and fail hard when the type is incorrect, or quietly translate e.g. dates such as that into strings...

**Comment by akx** [comment]
Closed via https://github.com/valohai/valohai-yaml/pull/31
