### ISSUE TITLE
Changing project will lock out --adhoc cli command

### ISSUE THREAD

**Issue by DrazenDodik** [valohai/valohai-cli#183]
I have several projects linked to the same repo.

If I do an --ad-hoc execution on project 1, then vh project link to project 2 and attempt to do an --ad-hoc execution there the cli will first say that the ad hoc commit has already been uploaded and then crash due to not finding the code commit in that project. So looks like the commit cache is not
aware of the possibility of changing projects.

**Comment by akx** [comment]
Related: #104

**Comment by DrazenDodik** [comment]
Closing as this should be fixed

**Comment by tokkoro** [comment]
For anyone reading this thread the parameter is not `--ad-hoc` but `--adhoc`
