### ISSUE TITLE
No SSH connection when starting an execution from the CLI

### ISSUE THREAD

**Issue by noorula** [valohai/valohai-cli#184]
Starting an execution from the command line with the SSH options doesn't give the machine IP in the logs. Moreover, when copying the execution, the SSH checkbox is unchecked as if the execution was started without the connection. 

`vh exec run --adhoc --debug-key-file=/tmp/my-debug-key.pub --debug-port 2222 mystep`

**Comment by memona008** [comment]
It's working fine for me
