### ISSUE TITLE
Upgrading valohai-cli does not update valohai-yaml

### ISSUE THREAD

**Issue by noorula** [valohai/valohai-cli#216]
I upgraded `valohai-cli` but kept getting error for pipeline parameters. Manually updating `valohai-yaml` solved this but from user perspective it would be better if there was only one component to update.

**Comment by akx** [comment]
You can run `pip install -U --upgrade-strategy=eager valohai-cli` to have pip upgrade `valohai-cli` and all dependencies too. But sure, no harm in bumping the minimum required `valohai-yaml` version in `valohai-cli` too :)

**Comment by teroyks** [comment]
@noorula This issue can probably be closed?

**Comment by noorula** [comment]
Sure thing! @teroyks
