### ISSUE TITLE
Commits not recognized in projects with custom yaml paths

### ISSUE THREAD

**Issue by noorula** [valohai/valohai-cli#241]
When running a non-adhoc execution from the cli in a project with custom path for `valohai.yaml` you get the following error: 
````
😩  Warning: Commit 5cd5042ec25980e1b9f32c2978f3dc8bc2e9ed0e is not known for the project. Have you pushed it?
Aborted!
````

It also seems that when fetching the repository to the project, there is a suffix added to the commit hash. Could this be the problem? 
````
😊  Success! Fetched: main (5cd5042ec25980e1b9f32c2978f3dc8bc2e9ed0e-mysubdir)
😊  Success! 1 new commits were fetched!
````

Running the execution from the UI and as an adhoc job both work fine.

**Comment by ruksi** [comment]
I was unable to reproduce the issue, could I get a bit more information e.g. the customer project and commands they ran?

1. I created a new git repo for a new Valohai project: https://github.com/ruksi/cosa-nostra and using `gun-trade/valohai.yaml` as the YAML path
2. ran `vh exec run greet`
3. It worked:

```
=>   /home/ruksi/Projects/cosa-nostra/valohai.yaml does not exist, assuming remote project
=>   Using project cosa-nostra in remote mode (in /home/ruksi/Projects/cosa-nostra)
=>   Using remote project cosa-nostra's newest commit 8c00d1fd134d5e48f7b11d68afd748ec1b2f296d-gun-trade
😁  Success! Execution #3 created. See http://127.0.0.1:8000/p/mafia/cosa-nostra/execution/018442d3-9da1-b386-4749-78622e1c5a50/
```

**Comment by noorula** [comment]
I was able to repro this myself yesterday. 🤔 It's an old project with old Git repo that I reorganized, i.e. created a new subdirectory for the `valohai.yaml` as that is what the customer is trying to do as well. I wonder if that's the difference here?

**Comment by ruksi** [comment]
:thinking: maybe it's related to `local` vs `remote` mode, I'll try to replicate it a bit more

**Comment by DrazenDodik** [comment]
<i>(related to <a href='https://valohai.zendesk.com/agent/tickets/1145'>Zendesk ticket #1145</a>)</i>
