### ISSUE TITLE
Incorrect error message when commit is not yet fetched

### ISSUE THREAD

**Issue by DrazenDodik** [valohai/valohai-cli#254]
Valohai-cli should ask if user want to fetch after Roi fails to find the commit. 

### User story:
When trying to run execution, got:

(research) MacBook-Pro-9:language\_modeling\_research $ vh execution run train  
😿 Warning: Commit e2780cc5ef7c54c4b56fb69cb2ca21cd06f81791 is not known for the project. Have you pushed it?

...  
but I had actually pushed the commit. Actually I had to click "Fetch repository" on the app page. I wonder why it cannot automatically fetch the repo? gz#1194

**Comment by tokkoro** [comment]
There's no technical reason why the fetch should be manual. So I would like to see that automated at some point. In the meantime, would be nice to have a UX feature in valohai-CLI that asks if you would like to fetch after "commit is not known for the project" error.
