### ISSUE TITLE
Step parameters with spaces don't work

### ISSUE THREAD

**Issue by ruksi** [valohai/valohai-cli#29]
Passing step parameters with spaces does't work, it does use such default parameters fine though.

Maybe we should require a separate `id` attribute in params for this? Or should we just slugify the name? Or enforce more strict naming for parameters?

Example below.

===========

```
(valohai-cli) bog:darknet-example ruksi$ vh exec run --step="Generate text" --'Textual Seed'=1
Usage: vh execution run [OPTIONS] [ARGS]...

Error: no such option: --Textual Seed
```

**Comment by akx** [comment]
PR #33 fixes this by slugifying the names, so that'd be `--textual-seed=1`.
In addition, it adds more human-friendly spel cheking for those arguments, so if you try `--tetxual-sed`, it'll try to help you.
