### ISSUE TITLE
Input/command validation should be done before ad-hoc packaging

### ISSUE THREAD

**Issue by akx** [valohai/valohai-cli#43]
It otherwise can take a long time for packaging to be done, only for the user to realize that they forgot a flag.

**Comment by JuhaKiili** [comment]
So far:
- Seemed like there isn't much to validate client-side
- Started creating server-side API to pre-validate execution creation
- Tried to re-use existing validator(s) for execution but they demand existing commit
- Can't have existing commit before packaging (?)

Feels like chicken-egg problem. Need some advice.

**Comment by akx** [comment]
Sorry if the issue was vague – I meant that as it is, let's say you run

```shell
$ vh exec --adhoc
```
it'll take a while to package, then upload files (let's say a hundred megs, so it takes a while), and only then you get the error that you need to name a step, too. (Or likewise if you ham-fist the name of a parameter; you get to wait for a minute only to get a `--lerning-ret: don't know what that is` sort of a message.

It would be better that ad-hoc packaging and upload is done as late as possible.

**Comment by JuhaKiili** [comment]
This is what confused me. If I run any of these:

`$ vh exec --adhoc`
`$ vh exec run --adhoc`
`$ vh exec run --adhoc notexistingstepname`
`$ vh exec run --adhoc --foobar greet-me`

It will give me error straight away and not package anything. Some information missing to reproduce the bug?

**Comment by akx** [comment]
Sorry, yeah, it's only about parameters/inputs, not the step name:

## valohai.yaml
```yaml
- step:
    name: hei
    command: hei
    image: busybox:latest
    parameters:
      - name: moi
        type: float
        optional: false
```
## shell
```
~/b/bigtest $ vh exec run --adhoc hei
Packaging /Users/akx/build/bigtest...
^_^  Success! Uploaded ad-hoc code 
Usage: vh execution run hei [OPTIONS]

Error: Missing option "--moi".
~/b/bigtest $
```
