### ISSUE TITLE
Make it easier to run valohai-cli

### ISSUE THREAD

**Issue by orasimus** [valohai/valohai-cli#66]
Enhance valohai-cli to work with pipsi and add steps for using it to Valohai documentation.

Currently pipsi fails valohai-cli installation with:
> Did not find any scripts. Uninstalling.

We should support pipsi as an alternative way of installing valohai-cli, because using pip installs it in a global namespace.

**Comment by akx** [comment]
Pipsi is not maintained, https://github.com/pipxproject/pipx is the new contender.
