### ISSUE TITLE
Typoed environment slug gives a confusing error message.

### ISSUE THREAD

**Issue by JuhaKiili** [valohai/valohai-cli#96]
If you use `environment: aws-eu-west-1-g2.2xlarge` instead of `environment: aws-eu-west-1-g2-2xlarge` in your `valohai.yaml`. You will get this error:

`API Error: * '' is not a valid UUID. (code: invalid)`

Note: Reported by user. Didn't verify this actually happens.

**Comment by akx** [comment]
The current error message is much better. I think we can call this done.

```
$ vh exec run --environment=blepblop --adhoc Train
😊  Success! Uploaded ad-hoc code!
API Error:
environment:
  * Object with slug or primary key blepblop does not exist. (code: does_not_exist)

Hint:
* Run `vh environments` to see the complete list of available environments.
```
